name: Bloat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-deps
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
        env:
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}