name: Pull Request Status Checks

on: pull_request

jobs:

  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  pRStatusGiphy:
    name: PR Status Giphy
    runs-on: ubuntu-latest
    steps:
      - name: PR Status Giphy
        uses: jzweifel/pr-status-giphy-action@master
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}