name: Todo-to-issue

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v1.1.1-beta"
        with:
#          INPUT_REPO: ${{ github.repository }}
#          INPUT_BEFORE: ${{ github.event.before }}
#          INPUT_SHA: ${{ github.sha }}
#          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO"
          COMMENT_MARKER: "//"
        id: "todo"