name: Todo-to-issue

on:
  push:
    branches: [ master ]

jobs:

  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: todo-actions
        uses: dtinth/todo-actions@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}